### ISSUE TITLE
Issue with single contribution not showing up

### ISSUE THREAD

**Issue by nickBlack4** [akerl-archived/githubchart#45]
I initially brought this issue up with someone else and they referred me to the gem here.  I'm going to paste below what I said,

I have a day that I only had one contribution when I forked another repository. The color is not showing up on the graph and so it shows as a day with zero contributions. I'm assuming this is a bug?

This can be seen on nickblackcode.com and my github is github.com/nickblack4

The day is March 1st that has one contribution not showing up on graph.

Cheers

**Comment by akerl** [comment]
I think you’re running into a time zone issue.

I’m able to replicate the behavior you’re seeing in githubchart’s output by opening your https://github.com/nickBlack4 in an incognito tab:

![B348DDC9-F208-48C5-A759-BEE993DF721E](https://user-images.githubusercontent.com/491209/75884716-59029900-5df3-11ea-8965-7b8d9b2419e0.jpeg)

Notably, the repo creation is shown here as being “March 2nd”.

Githubchart gets its data from https://github.com/akerl/githubstats , which parses from GitHub’s SVG on your user page, but it does so with an unauthenticated request, so it sees the activity the way GitHub displays it to an unauth’d use.

It’s not clear to me why they mismatch timestamps for events depending on the authentication level of the request :(

**Comment by nickBlack4** [comment]
This is interesting--thank you for the detail!
